services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    networks:
      - metics_frontend
    volumes:
      - backend-data:/app
    
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    networks:
      - metics_frontend
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - metics_frontend


networks:
  metics_frontend:
    driver: bridge
volumes:
  grafana-data:
  backend-data:
